apiVersion: v1
kind: Service
metadata:
  name: wallet-service-alb
  labels:
    app: wallet-service
spec:
  selector:
    app: wallet-service
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080